<?php

/** @var $block \Smile\ElasticsuiteCatalog\Block\Navigation\FilterRenderer */
/** @var $this \Smile\ElasticsuiteCatalog\Block\Navigation\Renderer\Attribute */
/** @var $escaper \Magento\Framework\Escaper  */

?>
<?php
  $uniqueId = '_' . uniqid();
  $jsLayout = $this->getJsLayout();
  $datascope = $this->getFilter()->getRequestVar() . 'Filter';
?>
<?php if (!empty($filterItems)) : ?>
    <?= $block->getChildBlock('attribute-filter-js')
        ->setUniqueId($uniqueId)
        ->setJsLayout($jsLayout)
        ->setScope($datascope)
        ->toHtml() ?>

    <div class="<?= $escaper->escapeHtml($datascope); ?>" x-data="initSmileAttibute<?= $uniqueId ?>()" x-init="initialize();">
        <div class="field search"  x-show="displaySearch">
            <div class="control">
                <input class="filter-search w-full mb-2"
                       type="text"
                       autocomplete="off"
                       :placeholder="searchPlaceholder"
                       @keyup="onSearchChange"
                       @focusout="onSearchFocusOut" />
            </div>
        </div>
        <ol class="items">
            <template x-for="attribute in displayedItems" hidden>
                <li class="item my-1">
                    <a x-on:click="filterByAjax()" x-show="attribute.count >= 1" :rel="options.displayRelNofollow">
                        <input type="checkbox"
                               :id="attribute.id"
                               :checked="attribute.is_selected"
                               :value="attribute.request_var"
                               :data-label="attribute.label"
                               />
                        <label :for="attribute.id" class="ml-2">
                            <span x-html="attribute.label"></span>
                            <span class="count" x-text="'(' + attribute.count + ')'" x-show ="options.displayProductCount"></span>
                        </label>
                    </a>

                    <div x-show="attribute.count < 1">
                        <span x-html="attribute.label"></span>
                        <span class="count" x-text="attribute.count"></span>
                    </div>
                </li>
            </template>
        </ol>

        <div class="no-results-message" x-model="result" x-show="getFulltextSearch() && !hasSearchResult()" class="empty">
            <p x-html="getSearchResultMessage()"></p>
        </div>

        <div class="actions" x-show="enableExpansion()">
            <div class="secondary text-right">
                <a class="action show-more underline text-secondary cursor-pointer" x-on:click="onShowMore()" x-show="displayShowMore()"><span x-text="showMoreLabel + '+'"></span></a>
                <a class="action show-less underline text-secondary cursor-pointer" x-on:click="onShowLess()" x-show="displayShowLess()"><span x-text="showLessLabel + '-'"></span></a>
            </div>
        </div>
    </div>

<?php endif; ?>
