<?php

declare(strict_types=1);

use Magento\Catalog\Block\Product\ProductList\Toolbar;
use Magento\Framework\Escaper;

/** @var Toolbar $block */
/** @var Escaper $escaper */

$availableLimitOptions = $block->getAvailableLimit();

?>

<?php if (count($availableLimitOptions) > 1): ?>
    <div class="field limiter flex items-center justify-center lg:justify-start col-span-3 xsm:col-span-1 lg:justify-center">
        <label class="hidden md:block text-sm mr-2 label" for="limiter">
            <span><?= $escaper->escapeHtml((string)__('Show')) ?></span>
        </label>
        <div class="control">
            <select aria-label="limiter" data-role="limiter" class="form-select limiter-options"
                    @change="changeLimiter(event.currentTarget.options[event.currentTarget.selectedIndex].value)">
                <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
                    <option value="<?= $escaper->escapeHtmlAttr($_key) ?>"
                        <?php if ($block->isLimitCurrent($_key)): ?>
                            selected="selected"
                        <?php endif ?>>
                        <?= $escaper->escapeHtml($_limit) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
        <span class="limiter-text text-sm ml-2 sr-only">
        <?= $escaper->escapeHtml(__('per page')) ?>
    </span>
    </div>
<?php else: ?>
    <div class="field limiter flex order-3 sm:order-2 md:order-3 lg:order-2 col-span-2 justify-end">

    </div>
<?php endif;
